---
language: python
python: "2.7"
sudo: required
services:
  - docker

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install sshpass
  - pip install -r tests/requirements.txt
  - ansible --version
  - pip freeze | grep docker

script:
  - python -c "import docker; print(docker.__file__, docker.__version__)"
  - ansible-galaxy install -r tests/requirements.yml
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ./tests/run-checks.sh
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
